const createSlice = require('@reduxjs/toolkit').createSlice
const createAsyncThunk = require('@reduxjs/toolkit').createAsyncThunk
const axios = require('axios')

const initialState = {
	loading: false,
	users: [],
	error: '',
}

// Generates Promise Lifecycle actions ('pending', 'fulfilled' and 'rejected' action types) but since those action types are not generated by userSlice you have to use extraReducers
const fetchUsers = createAsyncThunk('user/fetchUsers', () => {
	return axios
		.get('https://jsonplaceholder.typicode.com/users')
		.then((response) => response.data.map((user) => user.id))
})

const userSlice = createSlice({
	name: 'user',
	initialState,
	// since promise lifecycle actions types are not generated by userSlice, we use extraReducers instaed of reducers.
	extraReducers: (builder) => {
		builder.addCase(fetchUsers.pending, (state) => {
			state.loading = true
		})
		builder.addCase(fetchUsers.fulfilled, (state, action) => {
			state.loading = false
			state.users = action.payload
			state.error = ''
		})
		builder.addCase(fetchUsers.rejected, (state, action) => {
			state.loading = false
			state.users = []
			state.error = action.error.message
		})
	},
})

module.exports = userSlice.reducer
module.exports.fetchUsers = fetchUsers
